const stock = [
  {id:'LOT-260912-04',sku:'FR-001',name:'去骨雞腿排',category:'禽肉',batch:'C260912-A',location:'A-02-04',qty:486,unit:'箱',expiry:'2026-11-18',status:'正常',temp:'−21.2°C'},
  {id:'LOT-260906-11',sku:'FR-014',name:'挪威鮭魚切片',category:'水產',batch:'S260906-C',location:'A-01-02',qty:128,unit:'箱',expiry:'2026-10-12',status:'即將到期',temp:'−20.8°C'},
  {id:'LOT-260915-02',sku:'FR-008',name:'澳洲穀飼牛五花',category:'肉品',batch:'B260915-F',location:'B-03-01',qty:234,unit:'箱',expiry:'2027-02-24',status:'正常',temp:'−21.6°C'},
  {id:'LOT-260901-07',sku:'FR-021',name:'冷凍藍莓',category:'水果',batch:'F260901-D',location:'C-01-03',qty:92,unit:'箱',expiry:'2026-10-08',status:'即將到期',temp:'−19.9°C'},
  {id:'LOT-260914-05',sku:'FR-003',name:'白蝦仁 31/40',category:'水產',batch:'S260914-B',location:'A-04-06',qty:316,unit:'箱',expiry:'2027-03-30',status:'正常',temp:'−21.0°C'},
  {id:'LOT-260823-03',sku:'FR-032',name:'冷凍花椰菜',category:'蔬菜',batch:'V260823-E',location:'C-02-02',qty:0,unit:'箱',expiry:'2026-10-01',status:'待報廢',temp:'−18.4°C'},
  {id:'LOT-260918-09',sku:'FR-011',name:'紐西蘭羊肩排',category:'肉品',batch:'L260918-A',location:'B-01-05',qty:174,unit:'箱',expiry:'2027-01-16',status:'正常',temp:'−21.3°C'},
  {id:'LOT-260919-01',sku:'FR-026',name:'冷凍毛豆仁',category:'蔬菜',batch:'V260919-H',location:'C-03-04',qty:205,unit:'箱',expiry:'2027-04-10',status:'正常',temp:'−20.6°C'}
];
const warehouses=[{id:'WH-NAN',name:'竹南冷凍倉庫'},{id:'WH-SECOND',name:'竹南第二冷凍倉庫'}];
stock.forEach(item=>{item.warehouseId='WH-NAN';item.inboundAt='2026-09-01T09:00'});
stock.push(
 {id:'LOT-CABBAGE-OLD',sku:'VG-001',name:'高麗菜',category:'蔬菜',batch:'CABBAGE-260901',location:'A-01-01',qty:8,unit:'箱',expiry:'2026-11-30',status:'正常',temp:'−20.0°C',warehouseId:'WH-NAN',inboundAt:'2026-09-01T08:30'},
 {id:'LOT-CABBAGE-NEW',sku:'VG-001',name:'高麗菜',category:'蔬菜',batch:'CABBAGE-260915',location:'B-02-01',qty:6,unit:'箱',expiry:'2026-12-15',status:'正常',temp:'−20.4°C',warehouseId:'WH-SECOND',inboundAt:'2026-09-15T10:15'},
 {id:'LOT-LETTUCE',sku:'VG-002',name:'青江菜',category:'蔬菜',batch:'LETTUCE-260920',location:'A-03-02',qty:4,unit:'箱',expiry:'2026-10-30',status:'正常',temp:'−20.1°C',warehouseId:'WH-NAN',inboundAt:'2026-09-20T11:00'}
);
const acceptanceSeedStock=stock.filter(item=>['LOT-CABBAGE-OLD','LOT-CABBAGE-NEW','LOT-LETTUCE'].includes(item.id)).map(item=>({...item}));
// Keep the browser MVP usable without a server while preserving its work between sessions.
const STORAGE_KEY='shuangxu-wms-v1';
const audit=[];
try {
  const saved=globalThis.localStorage?.getItem(STORAGE_KEY);
  if(saved){const data=JSON.parse(saved);if(Array.isArray(data.stock))stock.splice(0,stock.length,...data.stock);if(Array.isArray(data.audit))audit.push(...data.audit)}
} catch (error) { /* Private browsing or invalid local data: continue with the sample dataset. */ }
acceptanceSeedStock.forEach(seed=>{if(!stock.some(item=>item.id===seed.id))stock.push({...seed})});
stock.forEach(item=>{item.warehouseId=item.warehouseId||'WH-NAN';item.inboundAt=item.inboundAt||'2026-09-01T09:00'});
function saveState(){try{globalThis.localStorage?.setItem(STORAGE_KEY,JSON.stringify({stock,audit,activities,workRecords,countRows,pickTasks}))}catch(error){toast('資料無法儲存於此瀏覽器',true)}}
function recordChange(change){Inventory.recordChange({stock,audit,countRows},change);saveState()}
const activities = [
  {type:'in',icon:'↙',text:'<b>王小美</b> 完成入庫驗收',detail:'IN-20260929-008 · 去骨雞腿排',time:'09:42',qty:'+ 48 箱'},
  {type:'out',icon:'↗',text:'<b>陳建宏</b> 完成揀貨出庫',detail:'OUT-20260929-021 · 全聯北區 DC',time:'09:18',qty:'− 32 箱'},
  {type:'warn',icon:'!',text:'<b>系統提醒</b> 藍莓批次即將到期',detail:'F260901-D · 剩餘 9 天',time:'08:56',qty:'92 箱'},
  {type:'in',icon:'☷',text:'<b>林志明</b> 完成 B 區儲位盤點',detail:'ST-20260928-006 · 差異 −2 箱',time:'昨日 16:31',qty:'已確認'}
];
let page='dashboard', dialogMode='', detailLot=null, activeCount=null;
let activeWarehouse='全部倉庫';
const content=document.querySelector('#page-content');
const dialog=document.querySelector('#action-dialog');
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n)=>new Intl.NumberFormat('zh-TW').format(n);
const totalQty=()=>stock.reduce((a,x)=>a+x.qty,0);
const usable=()=>stock.filter(x=>x.qty>0&&x.status!=='待報廢'&&!isCountLocked(x.id));
const dateText=new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date());
document.querySelector('#today-date').textContent=dateText;
function statusClass(s){return s==='正常'?'status-good':s==='即將到期'||s==='待確認'||s==='待盤點'||s==='盤點中'?'status-warn':s==='待報廢'?'status-danger':'status-neutral'}
function pill(s){return `<span class="status-pill ${statusClass(s)}">${esc(s)}</span>`}
function pageHead(eyebrow,title,desc,actions=''){return `<div class="page-heading"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${desc}</p></div><div class="heading-actions">${actions}</div></div>`}
function panelHead(title,subtitle='',action=''){return `<div class="panel-head"><div><div class="panel-title">${title}</div>${subtitle?`<div class="panel-subtitle">${subtitle}</div>`:''}</div>${action}</div>`}
function stockRows(list){if(!list.length)return '<tr><td colspan="8"><div class="empty-state">找不到符合條件的庫存</div></td></tr>';return list.map(x=>`<tr><td><span class="cell-main">${esc(x.name)}</span><span class="cell-sub">${esc(x.sku)} · ${esc(x.category)}</span></td><td>${esc(x.batch)}</td><td>${esc(x.location)}<span class="cell-sub">${esc(warehouses.find(w=>w.id===x.warehouseId)?.name||'')}</span></td><td><span class="cell-main">${fmt(x.qty)}</span> ${esc(x.unit)}</td><td>${esc(x.expiry)}</td><td>${esc(x.temp)}</td><td>${pill(isCountLocked(x.id)?'盤點中':x.status)}</td><td><button class="table-action" data-action="detail" data-id="${esc(x.id)}">查看</button></td></tr>`).join('')}
function dashboard(){const normal=stock.filter(x=>x.status==='正常').length,expiring=stock.filter(x=>x.status==='即將到期').length,overdueTasks=pickTasks.filter(task=>Inventory.isPickTaskOverdue(task)),todayRows=todayWorkRecords(),inboundToday=todayRows.filter(x=>x.type==='入庫'),outboundToday=todayRows.filter(x=>x.type==='出庫');return `${pageHead('TUESDAY · WAREHOUSE OVERVIEW','早安，志明 <span style="font-size:19px">☀</span>','以下是北區冷凍中心今日的營運概況。',`<button class="button" data-action="export"><span class="button-icon">⇩</span> 匯出報表</button><button class="button button-primary" data-action="inbound"><span>＋</span> 建立入庫單</button>`)}
  <div class="overview-grid">
    <article class="metric-card"><div class="metric-top">目前庫存總量 <span class="metric-icon">▤</span></div><div class="metric-value">${fmt(totalQty())}<small>箱</small></div><div class="metric-foot"><span class="positive">↗ 4.8%</span> 較上週同期</div><div class="metric-decoration">⌁</div></article>
    <article class="metric-card"><div class="metric-top">庫存品項 <span class="metric-icon">◈</span></div><div class="metric-value">128<small>項</small></div><div class="metric-foot">分布於 <span class="positive">12 個儲位</span></div><div class="metric-decoration">⌁</div></article>
    <article class="metric-card warning"><div class="metric-top">即將到期 <span class="metric-icon">◷</span></div><div class="metric-value">${expiring}<small>批次</small></div><div class="metric-foot"><span class="negative">需於 30 天內處理</span></div><div class="metric-decoration">⌁</div></article>
    <article class="metric-card"><div class="metric-top">今日出入庫 <span class="metric-icon">⇄</span></div><div class="metric-value">${todayRows.length}<small>筆</small></div><div class="metric-foot">入庫 ${inboundToday.length} 筆 <span style="color:#adb5b0">·</span> 出庫 ${outboundToday.length} 筆</div><div class="metric-decoration">⌁</div></article>
  </div>
  ${overdueTasks.length?`<div class="alert-row pick-overdue-warning" role="alert"><span class="alert-symbol">!</span><div class="alert-copy"><b>揀貨逾時警示</b><small>${overdueTasks.length} 筆揀貨任務超過 ${Math.round(Inventory.PICK_TASK_TIMEOUT_MS/60000)} 分鐘尚未確認，請到出庫作業處理。</small></div><button class="text-link" data-page="outbound">查看任務 →</button></div>`:''}
  <div class="content-grid"><section class="panel">${panelHead('庫存趨勢','近 7 日庫存量變化（箱）',`<div class="chart-legend"><span><i class="legend-dot"></i>入庫</span><span><i class="legend-dot orange"></i>出庫</span></div>`)}<div class="chart-wrap"><svg viewBox="0 0 640 174" preserveAspectRatio="none" role="img" aria-label="近七日庫存趨勢圖"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#6caa83" stop-opacity=".22"/><stop offset="1" stop-color="#6caa83" stop-opacity="0"/></linearGradient></defs><path class="chart-grid" d="M35 22H625M35 63H625M35 104H625M35 145H625"/><path class="chart-area" d="M35 126 L133 106 L231 115 L329 68 L427 78 L525 46 L625 55 L625 145 L35 145Z"/><path class="chart-line" d="M35 126 L133 106 L231 115 L329 68 L427 78 L525 46 L625 55"/><path class="chart-line-secondary" d="M35 96 L133 112 L231 88 L329 108 L427 92 L525 120 L625 101"/><circle class="chart-point" cx="525" cy="46" r="4"/><circle class="chart-point" cx="625" cy="55" r="4"/></svg></div><div class="chart-labels"><span>09/23</span><span>09/24</span><span>09/25</span><span>09/26</span><span>09/27</span><span>09/28</span><span>09/29</span></div></section>
  <section class="panel">${panelHead('效期提醒','建議優先安排出庫',`<button class="text-link" data-page="inventory">查看全部 →</button>`)}<div class="expiry-list">${stock.filter(x=>x.status==='即將到期').map(x=>{const days=Math.max(0,Math.ceil((new Date(x.expiry+'T00:00:00')-new Date())/86400000));return `<div class="expiry-row"><div><div class="expiry-name">${esc(x.name)}</div><div class="expiry-meta">批次 ${esc(x.batch)} · ${esc(x.location)}</div><div class="expiry-bar"><i style="width:${Math.max(18,Math.min(95,Math.round((35-days)/35*100)))}%"></i></div></div><div class="expiry-right"><div class="expiry-days">${days} 天後到期</div><div class="expiry-qty">${fmt(x.qty)} 箱</div></div></div>`}).join('')}</div><div class="alert-row"><span class="alert-symbol">!</span><div class="alert-copy"><b>冷凍庫 A 區溫度穩定</b><small>範圍 −20.8°C ～ −21.6°C · 設定 −18°C 以下</small></div><span class="alert-time">正常</span></div></section></div>
  <div class="content-grid"><section class="panel table-panel">${panelHead('庫存快速檢視','近期異動與效期優先批次',`<button class="text-link" data-page="inventory">前往庫存管理 →</button>`)}<div class="table-scroll"><table class="data-table"><thead><tr><th>商品</th><th>批次</th><th>儲位</th><th>可用庫存</th><th>有效期限</th><th>溫度</th><th>狀態</th><th></th></tr></thead><tbody>${stockRows([...stock].sort((a,b)=>a.expiry.localeCompare(b.expiry)).slice(0,4))}</tbody></table></div></section>
  <section class="panel">${panelHead('今日作業進度','北區冷凍中心 · 09/29') }<div class="progress-card"><div class="progress-top"><strong>76%</strong><span>日目標完成率</span></div><div class="progress-track"><i style="width:76%"></i></div><div class="progress-legend"><div><i class="legend-square"></i>已完成作業<b>13 筆</b></div><div><i class="legend-square orange"></i>待處理作業<b>4 筆</b></div><div><i class="legend-square gray"></i>今日預計<b>17 筆</b></div></div></div></section></div>
  <div class="bottom-grid"><section class="panel">${panelHead('最近作業','即時更新的倉庫活動紀錄',`<button class="text-link" data-page="stocktake">查看活動紀錄 →</button>`)}<div class="activity-list">${activities.slice(0,3).map(activityRow).join('')}</div></section><section class="panel">${panelHead('快速作業','開始一筆新的倉儲流程')}<div class="toolbar" style="padding:2px 15px 14px;display:grid;grid-template-columns:1fr 1fr"><button class="button button-quiet" data-action="inbound">↙　收貨入庫</button><button class="button button-quiet" data-action="outbound">↗　建立出庫</button><button class="button button-quiet" data-action="stocktake">☷　盤點登記</button><button class="button button-quiet" data-action="scrap">⌁　報廢登記</button></div></section></div>`}
function activityRow(a){return `<div class="activity-item"><span class="activity-mark ${a.type==='warn'?'mark-orange':a.type==='out'?'mark-blue':'mark-green'}">${a.icon}</span><div class="activity-copy">${a.text}<small>${a.detail} · ${a.time}</small></div><div class="activity-qty">${a.qty}</div></div>`}
function todayWorkRecords(){const today=new Date().toISOString().slice(0,10);return workRecords.filter(row=>row.recordedAt?.slice(0,10)===today)}
function recordQuantity(row){const value=Number(String(row.qty).replace(/[^0-9.]/g,''));return Number.isFinite(value)?value:0}
function pickTaskCards(){const tasks=pickTasks.filter(task=>['揀貨中','已揀貨待確認'].includes(task.status));if(!tasks.length)return '';return `<section class="panel pick-task-panel">${panelHead('待完成揀貨任務','按 FIFO 順序到儲位取貨；全部確認後才會扣帳。')}${tasks.map(task=>`<article class="pick-task" data-task-id="${esc(task.id)}"><div class="pick-task-head"><b>${esc(task.product)} · ${fmt(task.quantity)} 箱</b><span class="status-pill ${Inventory.isPickTaskOverdue(task)?'status-danger':'status-warn'}">${Inventory.isPickTaskOverdue(task)?'逾時待處理':esc(task.status)}</span></div><div class="pick-task-cards">${task.allocations.map((row,index)=>`<div class="pick-card ${row.confirmed?'pick-card-done':''}"><div><b>${esc(row.product||task.product)} · ${esc(row.batch)}</b><small>儲位 ${esc(row.location)} · 入庫 ${esc(row.inboundAt||'')} · ${fmt(row.qty)} 箱</small></div><button class="button ${row.confirmed?'button-quiet':'button-primary'}" data-action="confirm-pick" data-id="${esc(task.id)}" data-index="${index}" ${row.confirmed?'disabled':''}>${row.confirmed?'已取貨':'已取貨'}</button></div>`).join('')}</div><small class="pick-task-meta">出貨對象：${esc(task.partner)} · 建立於 ${new Date(task.createdAt).toLocaleString('zh-TW')}</small></article>`).join('')}</section>`}
function confirmPickTask(taskId,index){const result=Inventory.confirmPick({stock,audit,countRows,pickTasks,workRecords},{taskId,allocationIndex:index});if(!result.ok){toast(result.error,true);saveState();render();return}if(result.complete){const summary=result.plan.map(({item,qty})=>`${item.batch} ${qty}箱 @ ${item.location}`).join('、');activities.unshift({type:'out',icon:'↗',text:`<b>${esc(result.task.operator)}</b> 完成全部揀貨並出庫`,detail:`${esc(result.task.product)} · ${esc(summary)}`,time:'剛剛',qty:`− ${result.task.quantity} 箱`});toast(`全部批次已確認，出庫完成：${result.task.product} −${result.task.quantity} 箱`)}else toast(`已確認此批取貨，尚有 ${result.remaining} 張揀貨卡待確認`);saveState();render()}
function tablePanel(list,filtered=false){return `<section class="panel table-panel">${panelHead('庫存明細',`共 ${list.length} 個批次・可用庫存 ${fmt(list.reduce((a,x)=>a+x.qty,0))} 箱`)}<div class="toolbar"><label class="searchbox"><span>⌕</span><input id="stock-search" type="search" placeholder="搜尋商品、批次或儲位…" value="${filtered?esc(document.querySelector('#stock-search')?.value||''):''}"></label><select class="filter-select" id="warehouse-filter"><option value="全部倉庫" ${activeWarehouse==='全部倉庫'?'selected':''}>全部倉庫</option>${warehouses.map(w=>`<option value="${w.id}" ${activeWarehouse===w.id?'selected':''}>${esc(w.name)}</option>`).join('')}</select><select class="filter-select" id="status-filter"><option value="全部狀態">全部狀態</option><option>正常</option><option>即將到期</option><option>待報廢</option></select><select class="filter-select" id="category-filter"><option value="全部分類">全部分類</option>${[...new Set(stock.map(x=>x.category))].map(c=>`<option>${c}</option>`).join('')}</select><span class="toolbar-spacer"></span><button class="button button-small" data-action="export">⇩ 匯出 CSV</button></div><div class="table-scroll"><table class="data-table"><thead><tr><th>商品</th><th>批次編號</th><th>儲位</th><th>可用庫存</th><th>有效期限</th><th>庫內溫度</th><th>庫存狀態</th><th>操作</th></tr></thead><tbody id="stock-table-body">${stockRows(list)}</tbody></table></div><div class="summary-strip"><span>正常批次 <b>${list.filter(x=>x.status==='正常').length}</b></span><span>即將到期 <b>${list.filter(x=>x.status==='即將到期').length}</b></span><span>待報廢 <b>${list.filter(x=>x.status==='待報廢').length}</b></span></div></section>`}
function visibleStock(){return activeWarehouse==='全部倉庫'?stock:stock.filter(x=>x.warehouseId===activeWarehouse)}
function inventoryPage(){const shown=visibleStock();return `${pageHead('INVENTORY CONTROL','庫存管理','可依倉庫查看批次、數量、儲位與入庫時間。',`<button class="button" data-action="export">⇩ 匯出報表</button><button class="button" data-action="move">移動儲位</button><button class="button button-primary" data-action="inbound"><span>＋</span> 建立入庫單</button>`)}<div class="overview-grid"><article class="metric-card"><div class="metric-top">帳面庫存 <span class="metric-icon">▤</span></div><div class="metric-value">${fmt(shown.reduce((sum,x)=>sum+x.qty,0))}<small>箱</small></div><div class="metric-foot">${activeWarehouse==='全部倉庫'?'兩倉合計':esc(warehouses.find(w=>w.id===activeWarehouse)?.name||'倉庫')} · ${shown.length} 個批次</div></article><article class="metric-card"><div class="metric-top">可用庫存 <span class="metric-icon">◈</span></div><div class="metric-value">${fmt(shown.filter(x=>x.status!=='待報廢').reduce((sum,x)=>sum+x.qty,0))}<small>箱</small></div><div class="metric-foot">可供出庫與揀貨</div></article><article class="metric-card warning"><div class="metric-top">即將到期 <span class="metric-icon">◷</span></div><div class="metric-value">${shown.filter(x=>x.status==='即將到期').length}<small>批次</small></div><div class="metric-foot">效期 30 天內</div></article><article class="metric-card alert"><div class="metric-top">待處理報廢 <span class="metric-icon">⌁</span></div><div class="metric-value">${shown.filter(x=>x.status==='待報廢').length}<small>批次</small></div><div class="metric-foot">等待確認處理</div></article></div>${tablePanel(shown)}`}
const workRecords=[{id:'IN-20260929-008',type:'入庫',item:'去骨雞腿排',batch:'C260929-B',qty:'+48 箱',partner:'大成食品',operator:'王小美',time:'09/29 09:42',status:'已完成'},{id:'OUT-20260929-021',type:'出庫',item:'澳洲穀飼牛五花',batch:'B260915-F',qty:'−32 箱',partner:'全聯北區 DC',operator:'陳建宏',time:'09/29 09:18',status:'已完成'},{id:'IN-20260929-007',type:'入庫',item:'白蝦仁 31/40',batch:'S260929-D',qty:'+36 箱',partner:'海盛水產',operator:'王小美',time:'09/29 08:55',status:'已完成'},{id:'OUT-20260928-019',type:'出庫',item:'挪威鮭魚切片',batch:'S260906-C',qty:'−18 箱',partner:'家樂福物流',operator:'陳建宏',time:'09/28 16:47',status:'已完成'}];
function workPage(kind){const inbound=kind==='inbound';const rows=workRecords.filter(x=>x.type===(inbound?'入庫':'出庫')),todayRows=todayWorkRecords().filter(x=>x.type===(inbound?'入庫':'出庫')),todayQty=todayRows.reduce((sum,row)=>sum+recordQuantity(row),0);return `${pageHead(inbound?'INBOUND OPERATIONS':'OUTBOUND OPERATIONS',inbound?'入庫作業':'出庫作業',inbound?'登記到貨商品、批次與上架儲位。確認後即加入庫存。':'建立出庫需求，依效期建議揀貨並確認實際出庫數量。',`<button class="button button-primary" data-action="${kind}"><span>＋</span> 建立${inbound?'入庫':'出庫'}單</button>`)}<div class="overview-grid"><article class="metric-card"><div class="metric-top">今日${inbound?'入庫':'出庫'}單 <span class="metric-icon">${inbound?'↙':'↗'}</span></div><div class="metric-value">${todayRows.length}<small>筆</small></div><div class="metric-foot">已完成 ${todayRows.filter(x=>x.status==='已完成').length} 筆</div></article><article class="metric-card"><div class="metric-top">今日${inbound?'入庫':'出庫'}數量 <span class="metric-icon">▤</span></div><div class="metric-value">${fmt(todayQty)}<small>箱</small></div><div class="metric-foot">單位依商品設定</div></article><article class="metric-card warning"><div class="metric-top">處理中 <span class="metric-icon">◷</span></div><div class="metric-value">1<small>筆</small></div><div class="metric-foot">等待現場確認</div></article><article class="metric-card"><div class="metric-top">本月累計 <span class="metric-icon">▥</span></div><div class="metric-value">${inbound?'142':'168'}<small>筆</small></div><div class="metric-foot">較上月 <span class="positive">↗ 6.2%</span></div></article></div>${inbound?'':pickTaskCards()}<section class="panel table-panel">${panelHead(`最近${inbound?'入庫':'出庫'}單`,'模擬作業單據與現場處理狀態',`<button class="text-link" data-action="export">匯出紀錄 →</button>`)}<div class="table-scroll"><table class="data-table"><thead><tr><th>單據編號</th><th>商品／批次</th><th>${inbound?'供應商':'出貨對象'}</th><th>異動數量</th><th>作業人員</th><th>作業時間</th><th>狀態</th></tr></thead><tbody>${rows.map(x=>`<tr><td class="cell-main">${x.id}</td><td><span class="cell-main">${esc(x.item)}</span><span class="cell-sub">${esc(x.batch)}</span></td><td>${esc(x.partner)}</td><td class="cell-main">${x.qty}</td><td>${esc(x.operator)}</td><td>${x.time}</td><td>${pill(x.status==='已完成'?'正常':'待處理')}</td></tr>`).join('')}</tbody></table></div></section><div class="panel" style="margin-top:14px">${panelHead('作業提醒',inbound?'收貨後請確認批次、效期與實際上架儲位。':'系統依 FEFO 提示優先使用較早到期批次。')}<div class="alert-row"><span class="alert-symbol">${inbound?'↙':'↗'}</span><div class="alert-copy"><b>${inbound?'驗收時記錄到貨溫度，若超出商品保存範圍請登記異常。':'揀貨時核對商品與批次；已報廢庫存不可列入可出庫數量。'}</b><small>${inbound?'確認單據後，庫存會增加至指定儲位。':'出庫確認後，自動扣除對應批次的可用庫存。'}</small></div></div></div>`}
const countRows=[{id:'ST-20260929-003',scope:'冷凍庫 A 區 · 全區盤點',date:'2026-09-29',operator:'林志明',diff:'待盤點',status:'進行中'},{id:'ST-20260928-006',scope:'冷凍庫 B 區 · B-01 ～ B-03',date:'2026-09-28',operator:'林志明',diff:'−2 箱',status:'已確認'},{id:'SC-20260927-002',scope:'冷凍藍莓 · F260901-D',date:'2026-09-27',operator:'王小美',diff:'6 箱',status:'待確認報廢'}];
const pickTasks=[];
try{const saved=globalThis.localStorage?.getItem(STORAGE_KEY);if(saved){const data=JSON.parse(saved);if(Array.isArray(data.activities))activities.splice(0,activities.length,...data.activities);if(Array.isArray(data.workRecords))workRecords.splice(0,workRecords.length,...data.workRecords);if(Array.isArray(data.countRows))countRows.splice(0,countRows.length,...data.countRows);if(Array.isArray(data.pickTasks))pickTasks.splice(0,pickTasks.length,...data.pickTasks)}}catch(error){}
function stocktakePageCurrent(){const pending=countRows.filter(r=>r.status==='待確認'),today=new Date().toISOString().slice(0,10);return `${pageHead('STOCKTAKE & SCRAP','盤點與報廢','每日登記實盤結果；差異待主管確認後才會調整庫存。',`<button class="button" data-action="scrap">⌁ 登記報廢</button><button class="button button-primary" data-action="stocktake"><span>＋</span> 新增每日盤點</button>`)}<div class="overview-grid"><article class="metric-card"><div class="metric-top">待主管確認</div><div class="metric-value">${pending.length}<small>筆</small></div><div class="metric-foot">盤點不會立即改帳</div></article><article class="metric-card warning"><div class="metric-top">待確認差異</div><div class="metric-value">${pending.filter(r=>r.actualQty!==r.bookQty).length}<small>筆</small></div><div class="metric-foot">需主管覆核</div></article><article class="metric-card alert"><div class="metric-top">待確認報廢</div><div class="metric-value">${countRows.filter(r=>r.status==='待確認報廢').length}<small>筆</small></div><div class="metric-foot">確認後才扣除庫存</div></article><article class="metric-card"><div class="metric-top">今日盤點紀錄</div><div class="metric-value">${countRows.filter(r=>r.date===today).length}<small>筆</small></div><div class="metric-foot">可每日重複建立</div></article></div><section class="panel table-panel">${panelHead('盤點與報廢紀錄','待確認單據不會影響現有庫存')}<div class="table-scroll"><table class="data-table"><thead><tr><th>單據編號</th><th>盤點範圍／商品</th><th>建立日期</th><th>負責人</th><th>差異／數量</th><th>狀態</th><th></th></tr></thead><tbody>${countRows.map(r=>`<tr><td class="cell-main">${esc(r.id)}</td><td>${esc(r.scope)}</td><td>${esc(r.date)}</td><td>${esc(r.operator)}</td><td>${esc(r.diff)}</td><td>${pill(r.status)}</td><td>${r.status==='待確認'?`<button class="table-action" data-action="confirm-count" data-id="${esc(r.id)}">主管覆核</button>`:`<button class="table-action" data-action="record-detail" data-id="${esc(r.id)}">查看</button>`}</td></tr>`).join('')}</tbody></table></div></section><div class="panel" style="margin-top:14px">${panelHead('今日盤點作業','逐批次登記；有差異的項目交由主管確認')}<div class="activity-list">${activities.map(activityRow).join('')}</div></div>`}
function stocktakePageDaily(){const pending=countRows.filter(r=>r.status==='待確認'),unscanned=countRows.filter(r=>r.status==='待盤點'),today=new Date().toISOString().slice(0,10);return `${pageHead('STOCKTAKE & SCRAP','盤點與報廢','開始每日全倉盤點，逐批登記實盤量；盤點期間鎖定該批出入庫，差異由主管覆核。',`<button class="button" data-action="scrap">⌁ 登記報廢</button><button class="button" data-action="stocktake">單批補盤</button><button class="button button-primary" data-action="start-count">開始每日全倉盤點</button>`)}<div class="overview-grid"><article class="metric-card"><div class="metric-top">待實盤</div><div class="metric-value">${unscanned.length}<small>批</small></div><div class="metric-foot">逐列登記實際數量</div></article><article class="metric-card warning"><div class="metric-top">待主管覆核</div><div class="metric-value">${pending.length}<small>筆</small></div><div class="metric-foot">覆核前不改帳</div></article><article class="metric-card"><div class="metric-top">今日盤點單</div><div class="metric-value">${countRows.filter(r=>r.date===today).length}<small>筆</small></div><div class="metric-foot">按倉庫每日建立</div></article><article class="metric-card alert"><div class="metric-top">待確認報廢</div><div class="metric-value">${countRows.filter(r=>r.status==='待確認報廢').length}<small>筆</small></div><div class="metric-foot">覆核後才扣庫存</div></article></div><section class="panel table-panel">${panelHead('每日盤點／報廢單據','待實盤、待覆核批次會暫停出庫，避免盤點期間帳實變動。')}<div class="table-scroll"><table class="data-table"><thead><tr><th>單據</th><th>倉庫／儲位／商品批次</th><th>日期</th><th>負責人</th><th>帳面／差異</th><th>狀態</th><th>操作</th></tr></thead><tbody>${countRows.map(r=>`<tr><td class="cell-main">${esc(r.id)}</td><td>${esc(r.scope)}</td><td>${esc(r.date)}</td><td>${esc(r.operator)}</td><td>${r.status==='待盤點'?`${fmt(r.bookQty)} 箱 · 待實盤`:esc(r.diff)}</td><td>${pill(r.status)}</td><td>${r.status==='待盤點'?`<button class="table-action" data-action="record-count" data-id="${esc(r.id)}">登記實盤</button>`:r.status==='待確認'?`<button class="table-action" data-action="confirm-count" data-id="${esc(r.id)}">主管覆核</button>`:`<button class="table-action" data-action="record-detail" data-id="${esc(r.id)}">查看</button>`}</td></tr>`).join('')}</tbody></table></div></section><div class="panel" style="margin-top:14px">${panelHead('作業追溯','盤點差異確認後會新增庫存異動帳')}<div class="activity-list">${activities.map(activityRow).join('')}</div></div>`}
function stocktakePage(){return stocktakePageDaily()}
function reportsPage(){return `${pageHead('REPORTS & INSIGHTS','報表分析','快速掌握庫存周轉、效期風險與倉儲損耗。',`<button class="button" data-action="export">⇩ 匯出 CSV</button>`)}<div class="report-grid"><article class="report-card"><h3>庫存週轉概況</h3><strong>18.6 <small style="font-size:10px;color:#8e9b93;font-weight:500">天</small></strong><p>近 30 日平均庫存週轉天數 <span class="positive">↘ 2.1 天</span></p><div class="report-bars">${[46,61,55,72,50,80,65,91,76,65,88,96].map((v,i)=>`<i style="height:${v}%"></i>`).join('')}</div><div class="report-months"><span>08/31</span><span>09/07</span><span>09/14</span><span>09/21</span><span>09/29</span></div></article><article class="report-card"><h3>效期風險庫存</h3><strong>${fmt(stock.filter(x=>x.status==='即將到期').reduce((a,x)=>a+x.qty,0))} <small style="font-size:10px;color:#8e9b93;font-weight:500">箱</small></strong><p>2 個批次將於 30 天內到期</p><div class="report-bars">${[31,38,26,47,59,42,71,49,82,65,58,74].map(v=>`<i style="height:${v}%;background:#eddfcf"></i>`).join('')}</div><div class="report-months"><span>第 1 週</span><span>第 2 週</span><span>第 3 週</span><span>第 4 週</span></div></article><article class="report-card"><h3>本月盤點損耗</h3><strong>8 <small style="font-size:10px;color:#8e9b93;font-weight:500">箱</small></strong><p>報廢 6 箱 · 盤點差異 2 箱</p><div class="report-bars">${[58,39,68,44,78,51,37,63,47,72,56,41].map(v=>`<i style="height:${v}%;background:#f0dfdc"></i>`).join('')}</div><div class="report-months"><span>08/31</span><span>09/07</span><span>09/14</span><span>09/21</span><span>09/29</span></div></article></div><section class="panel" style="margin-top:14px">${panelHead('商品庫存分布','依商品分類彙總目前可用庫存')}<div class="table-scroll"><table class="data-table"><thead><tr><th>商品分類</th><th>庫存批次</th><th>庫存數量</th><th>占比</th><th>效期提醒</th></tr></thead><tbody>${['肉品','水產','禽肉','蔬菜','水果'].map((c,i)=>{const qty=[408,444,486,205,92][i];return `<tr><td class="cell-main">${c}</td><td>${[2,2,1,1,1][i]} 批</td><td>${qty} 箱</td><td><div class="progress-track" style="width:120px;height:5px"><i style="width:${Math.min(100,Math.round(qty/totalQty()*1000))}%"></i></div></td><td>${i===4?pill('即將到期'):pill('正常')}</td></tr>`}).join('')}</tbody></table></div></section>`}
function settingsPage(){return `${pageHead('MASTER DATA','基本資料','管理倉庫作業所需的商品、合作夥伴與儲位設定。',`<button class="button button-primary" data-action="settings-add"><span>＋</span> 新增資料</button>`)}<div class="settings-cards"><article class="settings-card"><span class="inline-tag">商品主檔 · 128 項</span><h3 style="margin-top:12px">商品與批次規則</h3><p>管理品名、分類、計量單位、批號與效期要求，以及商品建議保存溫度。</p><button class="button button-small" data-action="settings-view">查看商品資料 →</button></article><article class="settings-card"><span class="inline-tag">倉庫位置 · 12 個儲位</span><h3 style="margin-top:12px">倉庫與儲位</h3><p>北區冷凍中心 · 冷凍庫 A、B、C 區，管理儲位編號與溫度區間。</p><button class="button button-small" data-action="settings-view">查看儲位資料 →</button></article><article class="settings-card"><span class="inline-tag">合作夥伴 · 36 家</span><h3 style="margin-top:12px">客戶與供應商</h3><p>集中管理供應商與出貨對象聯絡資料，快速帶入入庫及出庫單。</p><button class="button button-small" data-action="settings-view">查看合作夥伴 →</button></article><article class="settings-card"><span class="inline-tag">使用者與角色 · 8 位</span><h3 style="margin-top:12px">帳號與作業權限</h3><p>倉庫管理員、現場作業人員與管理者。此 Demo 使用單一示範管理員。</p><button class="button button-small" data-action="settings-view">查看權限設定 →</button></article></div>`}
function render(){const titles={dashboard:'倉儲總覽',inventory:'庫存管理',inbound:'入庫作業',outbound:'出庫作業',stocktake:'盤點與報廢',reports:'報表分析',settings:'基本資料'};document.querySelector('#breadcrumb-current').textContent=titles[page]||titles.dashboard;const warehouseLabel=document.querySelector('#top-warehouse');if(warehouseLabel)warehouseLabel.textContent=activeWarehouse==='全部倉庫'?'全部倉庫':warehouses.find(w=>w.id===activeWarehouse)?.name||'全部倉庫';document.querySelectorAll('[data-page]').forEach(a=>a.classList.toggle('active',a.dataset.page===page));content.innerHTML=({dashboard,inventory:inventoryPage,inbound:()=>workPage('inbound'),outbound:()=>workPage('outbound'),stocktake:stocktakePage,reports:reportsPage,settings:settingsPage}[page]||dashboard)();}
function toast(message,error=false){const el=document.createElement('div');el.className=`toast${error?' error':''}`;el.textContent=message;document.querySelector('#toast-region').append(el);setTimeout(()=>el.remove(),3200)}
function options(){return usable().filter(x=>activeWarehouse==='全部倉庫'||x.warehouseId===activeWarehouse).sort((a,b)=>a.inboundAt.localeCompare(b.inboundAt)||a.expiry.localeCompare(b.expiry)).map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · ${esc(x.batch)}（入庫 ${esc(x.inboundAt.replace('T',' '))}／${esc(warehouses.find(w=>w.id===x.warehouseId)?.name||'')}／可用 ${x.qty} ${esc(x.unit)}）</option>`).join('')}
function isCountLocked(lotId){return Inventory.isCountLocked(countRows,lotId)}
function productOptions(warehouseId){const lots=usable().filter(x=>(!warehouseId||warehouseId==='全部倉庫'||x.warehouseId===warehouseId)&&!isCountLocked(x.id));return [...new Set(lots.map(x=>x.name))].sort().map(name=>{const batches=lots.filter(x=>x.name===name).sort((a,b)=>a.inboundAt.localeCompare(b.inboundAt)||a.expiry.localeCompare(b.expiry));return `<option value="${esc(name)}">${esc(name)}（最早批次 ${esc(batches[0].batch)} · ${esc(warehouses.find(w=>w.id===batches[0].warehouseId)?.name||'')}／${esc(batches[0].location)} · 入庫 ${esc(batches[0].inboundAt.replace('T',' '))} · 可用 ${fmt(batches.reduce((sum,x)=>sum+x.qty,0))} ${esc(batches[0].unit)}）</option>`}).join('')}
function planPick(product,warehouseId,quantity){return Inventory.planPick(stock,countRows,product,warehouseId,quantity)}
function refreshPickPreview(){const preview=document.querySelector('#pick-preview'),warehouse=document.querySelector('#f-warehouseId')?.value,product=document.querySelector('#f-product')?.value,qty=document.querySelector('#f-qty')?.value;if(!preview)return;const plan=planPick(product,warehouse,qty);if(!plan){preview.innerHTML='選擇商品並輸入數量後，系統會列出 FIFO 批次與儲位。';return}if(plan.insufficient){preview.innerHTML='此倉庫可用庫存不足，請調整數量或選擇其他倉庫。';return}preview.innerHTML=`揀貨順序（最早入庫優先）：<br>${plan.map(({item,qty:take})=>`${esc(item.batch)} · ${esc(item.location)} · 入庫 ${esc(item.inboundAt.replace('T',' '))} · ${take} 箱`).join('<br>')}<br><small>請依上列順序逐批掃描／輸入「批號@儲位」，每行一筆。</small>`}
function field(label,name,type='text',value='',full=false,placeholder=''){return `<div class="form-field${full===true||full==='true'?' full':''}"><label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${placeholder?`placeholder="${placeholder}"`:''} ${type==='number'&&name!=='temp'?'min="0"':''} required></div>`}
function selectField(label,name,opts,full=false){return `<div class="form-field${full?' full':''}"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}" required>${opts}</select></div>`}
function openDialog(mode,id){dialogMode=mode;detailLot=id?stock.find(x=>x.id===id):null;const body=document.querySelector('#dialog-body'),title=document.querySelector('#dialog-title'),submit=document.querySelector('#dialog-submit'),eyebrow=document.querySelector('#dialog-eyebrow');submit.hidden=false;let html='';
  if(mode==='inbound'){eyebrow.textContent='INBOUND · 收貨上架';title.textContent='建立入庫單';submit.innerHTML='確認入庫 <span>→</span>';html=`<div class="dialog-notice">確認收貨資料後，數量會加到指定倉庫與儲位，並記錄實際入庫時間。</div><div class="form-grid">${field('商品名稱','name','text','','true','例如：高麗菜')}${field('商品分類','category','text','','false','例如：蔬菜')}${field('入庫數量（箱）','qty','number','')}${field('批次編號','batch','text','','false','輸入批號')}${field('有效期限','expiry','date')}${field('上架儲位','location','text','','false','例如：A-02-04')}${selectField('入庫倉庫','warehouseId',warehouses.map(w=>`<option value="${w.id}" ${w.id===(activeWarehouse==='全部倉庫'?'WH-NAN':activeWarehouse)?'selected':''}>${esc(w.name)}</option>`).join(''))}${field('入庫時間','inboundAt','datetime-local',new Date().toISOString().slice(0,16))}${field('供應商','partner','text','','true','輸入供應商名稱')}${field('到貨溫度（°C）','temp','number','-20.5')}${field('備註','reason','text','','true','選填')}</div>`}
  else if(mode==='outbound'){eyebrow.textContent='OUTBOUND · FIFO PICK TASK';title.textContent='建立出庫揀貨任務';submit.innerHTML='建立揀貨任務 <span>→</span>';const defaultWarehouse=activeWarehouse==='全部倉庫'?'WH-NAN':activeWarehouse;const warehouseChoices=warehouses.map(w=>`<option value="${w.id}" ${w.id===defaultWarehouse?'selected':''}>${esc(w.name)}</option>`).join('');html=`<div class="dialog-notice">系統會依最早入庫批次建立揀貨卡片。請到指定儲位取貨並逐張按「已取貨」；所有批次確認後才扣帳。</div><div class="form-grid">${selectField('出庫倉庫','warehouseId',warehouseChoices)}${selectField('出庫商品','product',productOptions(defaultWarehouse),true)}${field('出庫數量（箱）','qty','number','')}<div id="pick-preview" class="dialog-notice full">選擇商品並輸入數量後，系統會列出 FIFO 批次與儲位。</div>${field('出貨對象','partner','text','','true','例如：客戶名稱')}${field('揀貨人員','operator','text','林志明')}${field('出庫備註','reason','text','','true','選填')}</div>`}
  else if(mode==='move'){eyebrow.textContent='LOCATION MOVE · 移庫';title.textContent='更新批次儲位';submit.innerHTML='確認移庫 <span>→</span>';html=`<div class="dialog-notice">移庫只更新儲位，不改變庫存數量；系統會記錄原儲位、目的儲位與操作人。</div><div class="form-grid">${selectField('商品／批次','lot',stock.filter(x=>activeWarehouse==='全部倉庫'||x.warehouseId===activeWarehouse).map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · ${esc(x.batch)}（${esc(x.location)}）</option>`).join(''),true)}${field('新儲位','location','text','','true','例如：A-04-02')}${field('操作人','operator','text','林志明')}${field('移庫原因','reason','text','','true','例如：庫位整理')}</div>`}
  else if(mode==='stocktake'){eyebrow.textContent='CYCLE COUNT · DAILY COUNT';title.textContent='登記盤點結果';submit.innerHTML='送交主管確認 <span>→</span>';html=`<div class="dialog-notice">每日盤點時登記帳面批次與實際數量、差異原因。此步驟只建立待確認盤點單，不會更改庫存；主管確認後才過帳。</div><div class="form-grid">${selectField('盤點商品／批次','lot',options(),true)}${field('實際盤點數量（箱）','qty','number','')}${selectField('差異原因','reason',[['','請選擇差異原因'],['例行盤點差異','例行盤點差異'],['腐爛／不可售','腐爛／不可售'],['包裝破損','包裝破損'],['收發貨記錄有誤','收發貨記錄有誤'],['其他','其他']].map(x=>`<option value="${esc(x[0])}">${esc(x[1])}</option>`).join(''),true)}${field('盤點負責人','operator','text','林志明')}</div>`}
  else if(mode==='start-count'){eyebrow.textContent='DAILY CYCLE COUNT';title.textContent='開始每日全倉盤點';submit.innerHTML='建立批次盤點清單 <span>→</span>';const defaultWarehouse=activeWarehouse==='全部倉庫'?'WH-NAN':activeWarehouse;html=`<div class="dialog-notice">建立所選倉庫所有批次的今日盤點任務。任務建立後會暫停這些批次的出庫，直到差異完成主管覆核。</div><div class="form-grid">${selectField('盤點倉庫','warehouseId',warehouses.map(w=>`<option value="${w.id}" ${w.id===defaultWarehouse?'selected':''}>${esc(w.name)}</option>`).join(''))}${field('盤點負責人','operator','text','林志明')}</div>`}
  else if(mode==='record-count'){activeCount=countRows.find(row=>row.id===id);const item=stock.find(x=>x.id===activeCount?.lotId);eyebrow.textContent='DAILY CYCLE COUNT';title.textContent='登記實際盤點數';submit.innerHTML='送交主管覆核 <span>→</span>';if(!activeCount||activeCount.status!=='待盤點'||!item){dialog.close();toast('此盤點任務已處理或不存在',true);return}html=`<div class="dialog-notice">核對儲位實物後填入數量。庫存差異會暫存，主管覆核前不會調整帳面庫存。</div><div class="detail-list"><div class="detail-item"><small>批次／儲位</small><b>${esc(item.batch)} · ${esc(item.location)}</b></div><div class="detail-item"><small>帳面數量</small><b>${fmt(activeCount.bookQty)} 箱</b></div></div><div class="form-grid">${field('實際盤點數量（箱）','qty','number','')}${selectField('差異原因','reason',[['','請選擇差異原因'],['帳實相符','帳實相符'],['腐爛／不可售','腐爛／不可售'],['包裝破損','包裝破損'],['收發貨記錄有誤','收發貨記錄有誤'],['其他','其他']].map(x=>`<option value="${esc(x[0])}">${esc(x[1])}</option>`).join(''),true)}${field('盤點負責人','operator','text',activeCount.operator)}</div>`}
  else if(mode==='confirm-count'){activeCount=countRows.find(row=>row.id===id);eyebrow.textContent='STOCKTAKE REVIEW · 主管覆核';title.textContent='確認盤點差異';submit.innerHTML='確認並調整庫存 <span>→</span>';if(!activeCount||activeCount.status!=='待確認'){dialog.close();toast('此盤點單已處理或不存在',true);return}html=`<div class="dialog-notice warning">確認後才會依實盤數量調整庫存，並新增異動帳。</div><div class="detail-list"><div class="detail-item"><small>商品批次</small><b>${esc(activeCount.scope)}</b></div><div class="detail-item"><small>帳面數量</small><b>${fmt(activeCount.bookQty)} 箱</b></div><div class="detail-item"><small>實盤數量</small><b>${fmt(activeCount.actualQty)} 箱</b></div><div class="detail-item"><small>差異原因</small><b>${esc(activeCount.reason)}</b></div><div class="detail-item"><small>盤點人</small><b>${esc(activeCount.operator)}</b></div></div>`}
 else if(mode==='scrap'){eyebrow.textContent='SCRAP · 損耗管理';title.textContent='登記不可售報廢';submit.innerHTML='確認報廢入帳 <span>→</span>';html=`<div class="dialog-notice warning">報廢入帳後會從可用庫存扣除數量，並保留批號、原因與操作人紀錄。</div><div class="form-grid">${selectField('報廢商品／批次','lot',stock.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · ${esc(x.batch)}（帳面 ${x.qty} ${esc(x.unit)}）</option>`).join(''),true)}${field('報廢數量（箱）','qty','number','')}${selectField('報廢原因','reason',[['','請選擇報廢原因'],['腐爛／變質','腐爛／變質'],['包裝破損','包裝破損'],['溫度異常','溫度異常'],['過期','過期'],['其他','其他']].map(x=>`<option value="${esc(x[0])}">${esc(x[1])}</option>`).join(''),true)}${field('經手人','operator','text','林志明')}</div>`}
  else if(mode==='detail'){eyebrow.textContent='LOT TRACEABILITY · 批次追溯';title.textContent=detailLot?.name||'庫存明細';submit.hidden=true;const x=detailLot;if(!x){dialog.close();return}const history=audit.filter(entry=>entry.lot===x.id);html=`<div class="dialog-notice">從入庫到目前庫位的批次庫存摘要。</div><div class="detail-list"><div class="detail-item"><small>商品編號</small><b>${esc(x.sku)}</b></div><div class="detail-item"><small>批次編號</small><b>${esc(x.batch)}</b></div><div class="detail-item"><small>倉庫</small><b>${esc(warehouses.find(w=>w.id===x.warehouseId)?.name||'')}</b></div><div class="detail-item"><small>目前儲位</small><b>${esc(x.location)}</b></div><div class="detail-item"><small>入庫時間</small><b>${esc(x.inboundAt.replace('T',' '))}</b></div><div class="detail-item"><small>可用庫存</small><b>${fmt(x.qty)} ${esc(x.unit)}</b></div><div class="detail-item"><small>有效期限</small><b>${esc(x.expiry)}</b></div><div class="detail-item"><small>庫內溫度</small><b>${esc(x.temp)}</b></div><div class="detail-item"><small>庫存狀態</small><b>${esc(x.status)}</b></div></div><div class="panel" style="margin-top:14px">${panelHead('批次異動紀錄')}<div class="activity-list">${history.length?history.map(entry=>`<div class="activity-item"><span class="activity-mark mark-green">↔</span><div class="activity-copy"><b>${esc(entry.type)} · ${esc(entry.documentId)}</b><small>${esc(entry.reason)} · ${esc(entry.operator)} · ${esc(entry.time)}</small></div><div class="activity-qty">${esc(entry.quantity)}</div></div>`).join(''):'<div class="empty-state">尚無異動紀錄</div>'}</div></div>`}
 else if(mode==='record-detail'){eyebrow.textContent='RECORD DETAIL · 作業追溯';title.textContent='作業單據明細';submit.hidden=true;html=`<div class="dialog-notice">差異盤點完成後由主管確認，報廢品另列原因以便損耗分析。</div><div class="detail-list"><div class="detail-item"><small>帳面庫存</small><b>86 箱</b></div><div class="detail-item"><small>實際盤點</small><b>84 箱</b></div><div class="detail-item"><small>差異數量</small><b style="color:#c87857">−2 箱</b></div><div class="detail-item"><small>差異原因</small><b>外箱破損</b></div><div class="detail-item"><small>操作人</small><b>林志明</b></div><div class="detail-item"><small>確認狀態</small><b>主管已確認</b></div></div>`}
 else if(mode==='settings-view'||mode==='settings-add'){eyebrow.textContent='MASTER DATA · 基本資料';title.textContent=mode==='settings-add'?'新增商品資料':'示範基本資料';submit.hidden=true;html=`<div class="dialog-notice">此 Demo 以模擬資料呈現，基本資料維護流程尚未接入。</div><div class="detail-list"><div class="detail-item"><small>庫存商品</small><b>128 項</b></div><div class="detail-item"><small>合作夥伴</small><b>36 家</b></div><div class="detail-item"><small>倉庫儲位</small><b>12 個</b></div><div class="detail-item"><small>溫控範圍</small><b>−18°C 以下</b></div></div>`}
 body.innerHTML=html;submit.hidden=['detail','record-detail','settings-view','settings-add'].includes(mode);dialog.showModal()}
function action(action,id,index){if(action==='detail')return openDialog('detail',id);if(action==='record-detail')return openDialog('record-detail');if(action==='confirm-pick')return confirmPickTask(id,index);if(['record-count','confirm-count'].includes(action))return openDialog(action,id);if(['start-count','inbound','outbound','stocktake','scrap','move','settings-view','settings-add'].includes(action))return openDialog(action);if(action==='export')return exportCsv();}
function exportCsv(){const rows=[['商品','分類','批次','儲位','庫存','單位','有效期限','狀態'],...stock.map(x=>[x.name,x.category,x.batch,x.location,x.qty,x.unit,x.expiry,x.status])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='冷凍倉儲庫存報表.csv';a.click();URL.revokeObjectURL(url);toast('庫存 CSV 已下載')}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){e.preventDefault();page=nav.dataset.page;render();return}const actionEl=e.target.closest('[data-action]');if(actionEl){action(actionEl.dataset.action,actionEl.dataset.id,actionEl.dataset.index);return}if(e.target.closest('.close-dialog'))dialog.close()});
content.addEventListener('input',e=>{if(['stock-search','warehouse-filter','status-filter','category-filter'].includes(e.target.id))filterStock()});
function filterStock(){const q=(document.querySelector('#stock-search')?.value||'').trim().toLowerCase(),status=document.querySelector('#status-filter')?.value||'全部狀態',category=document.querySelector('#category-filter')?.value||'全部分類',warehouse=document.querySelector('#warehouse-filter')?.value||activeWarehouse;activeWarehouse=warehouse;const list=visibleStock().filter(x=>(status==='全部狀態'||x.status===status)&&(category==='全部分類'||x.category===category)&&(!q||[x.name,x.sku,x.batch,x.location].some(v=>v.toLowerCase().includes(q))));const tbody=document.querySelector('#stock-table-body');if(tbody)tbody.innerHTML=stockRows(list)}
document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>dialog.close()));
content.addEventListener('input',e=>{if(e.target.id==='warehouse-filter'){const label=document.querySelector('#top-warehouse');if(label)label.textContent=activeWarehouse==='全部倉庫'?'全部倉庫':warehouses.find(w=>w.id===activeWarehouse)?.name||'全部倉庫'}});
document.querySelector('#action-form').addEventListener('change',e=>{if(dialogMode==='outbound'&&e.target.name==='warehouseId'){const product=document.querySelector('#f-product');if(product)product.innerHTML=productOptions(e.target.value)}if(dialogMode==='outbound')refreshPickPreview()});
document.querySelector('#action-form').addEventListener('input',e=>{if(dialogMode==='outbound'&&['product','qty'].includes(e.target.name))refreshPickPreview()});
document.querySelector('#action-form').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),v=Object.fromEntries(fd.entries());const qty=Number(v.qty);const lockedTarget=dialogMode==='inbound'?stock.find(x=>x.name.toLowerCase()===String(v.name||'').trim().toLowerCase()&&x.batch.toLowerCase()===String(v.batch||'').trim().toLowerCase()&&x.warehouseId===(v.warehouseId||'WH-NAN'))?.id:['move','scrap'].includes(dialogMode)?v.lot:null;if(lockedTarget&&isCountLocked(lockedTarget)){toast('此批次盤點中，完成主管覆核前不能移庫或異動庫存',true);return}
 if(dialogMode==='inbound'){const warehouseId=v.warehouseId||'WH-NAN',docId=`IN-${Date.now()}`,result=Inventory.receive({stock,audit,countRows},{name:v.name,category:v.category||'其他',qty,batch:v.batch,expiry:v.expiry||'2027-06-30',location:v.location,warehouseId,inboundAt:v.inboundAt,temp:`${v.temp||'-20.5'}°C`,sku:`FR-${String(stock.length+1).padStart(3,'0')}`,id:`LOT-${Date.now()}`,partner:v.partner,operator:v.operator||'林志明',reason:v.reason||'收貨上架',documentId:docId});if(!result.ok){toast(result.error,true);return}const item=result.item;activities.unshift({type:'in',icon:'↙',text:`<b>${esc(v.operator||'林志明')}</b> 完成入庫驗收`,detail:`${esc(item.name)} · ${esc(item.batch)} · ${esc(warehouses.find(w=>w.id===warehouseId)?.name||'')}`,time:'剛剛',qty:`+ ${qty} 箱`});workRecords.unshift({id:docId,type:'入庫',item:item.name,batch:item.batch,qty:`+${qty} 箱`,partner:v.partner||'未指定',operator:v.operator||'林志明',time:new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'}),recordedAt:new Date().toISOString(),status:'已完成'});if(Number(v.temp)>-18){const anomalyReason=`收貨溫度 ${v.temp}°C 超出 -18°C 保存上限`;Inventory.recordChange({stock,audit,countRows},{lot:item.id,type:'溫度異常',quantity:`${v.temp}°C`,reason:anomalyReason,operator:v.operator||'林志明',documentId:docId});activities.unshift({type:'warn',icon:'!',text:'<b>溫度異常</b> 收貨溫度超出保存上限',detail:`${esc(item.name)} · ${esc(item.batch)} · ${esc(anomalyReason)}`,time:'剛剛',qty:`${v.temp}°C`})}toast(`入庫完成：${item.name} +${qty} 箱`)}
 else if(dialogMode==='move'){const result=Inventory.move({stock,audit,countRows},{lotId:v.lot,location:v.location.trim(),reason:v.reason,operator:v.operator||'林志明'});if(!result.ok){toast(result.error,true);return}const {item,previous,documentId}=result;activities.unshift({type:'in',icon:'⇄',text:`<b>${esc(v.operator||'林志明')}</b> 完成移庫`,detail:`${esc(item.name)} · ${esc(item.batch)} · ${esc(previous)} → ${esc(item.location)}`,time:'剛剛',qty:'儲位更新'});toast(`儲位已更新：${item.name} → ${item.location}`)}
  else if(dialogMode==='outbound'){const warehouseId=v.warehouseId||'WH-NAN',result=Inventory.createPickTask({stock,audit,countRows,pickTasks,workRecords},{product:v.product,warehouseId,quantity:qty,operator:v.operator||'林志明',partner:v.partner||'未指定',reason:v.reason||''});if(!result.ok){toast(result.error,true);return}const task=result.task,summary=task.allocations.map(row=>`${row.batch} ${row.qty}箱 @ ${row.location}`).join('、');activities.unshift({type:'warn',icon:'↗',text:`<b>${esc(task.operator)}</b> 建立揀貨任務，等待逐批取貨確認`,detail:`${esc(task.product)} · ${esc(summary)}`,time:'剛剛',qty:`${task.quantity} 箱 · 揀貨中`});toast(`揀貨任務已建立：${task.allocations.length} 張批次卡；全部確認後才會扣帳`)}
  else if(dialogMode==='start-count'){const warehouseId=v.warehouseId,result=Inventory.startCount({stock,audit,countRows},{warehouseId,operator:v.operator||'林志明'});if(!result.ok){toast(result.error,true);return}result.rows.forEach(row=>{const item=stock.find(entry=>entry.id===row.lotId);row.scope=`${warehouses.find(w=>w.id===warehouseId)?.name||''} · ${row.scope}`});activities.unshift({type:'warn',icon:'☷',text:`<b>${esc(v.operator||'林志明')}</b> 開始每日全倉盤點`,detail:`${esc(warehouses.find(w=>w.id===warehouseId)?.name||'')} · ${result.rows.length} 個批次已鎖定待實盤`,time:'剛剛',qty:'盤點中'});toast(`盤點任務已建立：${result.rows.length} 個批次；任務完成前暫停這些批次出庫`)}
  else if(dialogMode==='record-count'){const result=Inventory.recordCount({stock,audit,countRows},{rowId:activeCount?.id,actualQty:qty,reason:v.reason,operator:v.operator});if(result.voided){saveState();toast(result.error,true);return}if(!result.ok){toast(result.error,true);return}const {row,diff}=result,item=stock.find(x=>x.id===row.lotId);activities.unshift({type:'warn',icon:'☷',text:`<b>${esc(row.operator)}</b> 登記實盤數，待主管覆核`,detail:`${esc(item.name)} · 帳面 ${row.bookQty} 箱／實盤 ${qty} 箱 · ${esc(v.reason)}`,time:'剛剛',qty:'待覆核'});toast('實盤結果已提交；覆核前庫存維持原數量')}
  else if(dialogMode==='stocktake'){const item=stock.find(x=>x.id===v.lot),result=Inventory.submitCount({stock,audit,countRows},{lotId:v.lot,actualQty:qty,reason:v.reason,operator:v.operator||'林志明'});if(!result.ok){toast(result.error,true);return}const {row}=result;row.scope=`${warehouses.find(w=>w.id===item.warehouseId)?.name||''} · ${row.scope}`;activities.unshift({type:'warn',icon:'☷',text:`<b>${esc(row.operator)}</b> 提交盤點，待主管確認`,detail:`${esc(item.name)} · 帳面 ${item.qty} 箱／實盤 ${qty} 箱 · ${esc(v.reason)}`,time:'剛剛',qty:'待確認'});toast('盤點已提交；確認前庫存不變')}
  else if(dialogMode==='confirm-count'){const result=Inventory.approveCount({stock,audit,countRows},{rowId:activeCount?.id,operator:'林志明'});if(!result.ok){toast(result.error,true);return}const {item,diff,row}=result;activities.unshift({type:'in',icon:'☷',text:'<b>林志明</b> 確認盤點並入帳',detail:`${esc(item.name)} · 差異 ${diff>0?'+':''}${diff} 箱 · ${esc(row.reason)}`,time:'剛剛',qty:'已確認'});toast(diff===0?'盤點完成：帳實相符':`盤點已確認：庫存調整 ${diff>0?'+':''}${diff} 箱`)}
 else if(dialogMode==='scrap'){const item=stock.find(x=>x.id===v.lot),result=Inventory.scrap({stock,audit,countRows},{lotId:v.lot,quantity:qty,reason:v.reason,operator:v.operator||'林志明'});if(!result.ok){toast(`${result.error}（${item?.qty||0} 箱）`,true);return}activities.unshift({type:'warn',icon:'⌁',text:`<b>${esc(v.operator||'林志明')}</b> 完成報廢處理`,detail:`${esc(item.name)} · ${esc(item.batch)} · ${esc(v.reason)}`,time:'剛剛',qty:`− ${qty} 箱`});countRows.unshift({id:result.documentId,scope:`${item.name} · ${item.batch}`,date:new Date().toISOString().slice(0,10),operator:v.operator||'林志明',diff:`${qty} 箱`,status:'已確認報廢'});toast(`報廢已入帳：${item.name} −${qty} 箱`)}
 saveState();dialog.close();render();});
render();
